import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({ page: { padding: 32, fontSize: 10, color: "#1c1917" }, title: { fontSize: 20, fontWeight: 700, marginBottom: 6 }, muted: { color: "#57534e", lineHeight: 1.5 }, section: { marginTop: 16 }, heading: { fontSize: 12, fontWeight: 700, borderBottomWidth: 1, borderBottomColor: "#d6d3d1", paddingBottom: 4, marginBottom: 6 }, row: { marginBottom: 4 } });
type Item = Record<string, unknown>;
type RdoPdf = { date: string; status: string; weather_morning: string; weather_afternoon: string; notes: string | null; projects: { name: string; address: string }; rdo_labor: Item[]; rdo_equipment: Item[]; rdo_activities: Item[]; rdo_occurrences: Item[] };
function List({ items, children }: { items: Item[]; children: (item: Item) => string }) { return <>{items.length ? items.map((item, index) => <Text key={index} style={styles.row}>• {children(item)}</Text>) : <Text style={styles.muted}>Não informado.</Text>}</>; }

export function RdoDocument({ rdo }: { rdo: RdoPdf }) {
  return <Document title={`RDO ${rdo.date}`}><Page size="A4" style={styles.page}><Text style={styles.title}>Relatório Diário de Obra</Text><Text style={styles.muted}>{rdo.projects.name}{"\n"}{rdo.projects.address}{"\n"}Data: {rdo.date} | Status: {rdo.status}</Text><View style={styles.section}><Text style={styles.heading}>Condições climáticas</Text><Text>Manhã: {rdo.weather_morning} | Tarde: {rdo.weather_afternoon}</Text></View><View style={styles.section}><Text style={styles.heading}>Mão de obra</Text><List items={rdo.rdo_labor}>{(item) => `${item.quantity} ${item.role_name}${item.is_outsourced ? " (terceirizada)" : ""}`}</List></View><View style={styles.section}><Text style={styles.heading}>Equipamentos</Text><List items={rdo.rdo_equipment}>{(item) => `${item.quantity} ${item.type_name}`}</List></View><View style={styles.section}><Text style={styles.heading}>Atividades realizadas</Text><List items={rdo.rdo_activities}>{(item) => `${item.description} (${item.status})`}</List></View><View style={styles.section}><Text style={styles.heading}>Ocorrências</Text><List items={rdo.rdo_occurrences}>{(item) => String(item.description)}</List></View><View style={styles.section}><Text style={styles.heading}>Observações</Text><Text>{rdo.notes || "Não informado."}</Text></View></Page></Document>;
}
